name: Rellenar IDs de TMDB

on:
  workflow_dispatch: # Botón para lanzarlo a mano

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests supabase
      - name: Ejecutar Buscador de IDs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python actualizar_tmdb.py
